import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Book App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <p className="ms-2 me">
          Why Programming? You may already have used software, perhaps for word
          processing or spreadsheets, to solve problems. Perhaps now you are
          curious to learn how programmers write software. A program is a set of
          step-by-step instructions that directs the computer to do the tasks
          you want it to do and produce the results you want.{" "}
        </p>
      </article>
    </div>
  );
};

export default Home;
